name: rider
description: A new Flutter project.
publish_to: 'none'
version: 3.0.0+16

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  analog_clock: ^0.1.1
  audioplayers: ^6.1.0
  blurry_modal_progress_hud: ^1.1.1
  cached_network_image: ^3.3.1
  carousel_slider: ^5.0.0
  connectivity_plus: ^6.1.1
  device_info_plus: ^11.2.0
  dio: ^5.4.0
  equatable: ^2.0.5
  file_picker: ^8.1.6
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.6
  flutter:
    sdk: flutter
  flutter_animate: ^4.4.0
  flutter_local_notifications: ^18.0.1
  flutter_pdfview: ^1.3.2
  flutter_rating_bar: ^4.0.1
  flutter_ringtone_player: ^4.0.0+3
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.10+1
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  get: ^4.7.2
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.3
  http: ^1.1.0
  image_picker: ^1.0.7
  intl: ^0.20.1
  path: ^1.9.0
  path_provider: ^2.1.5
  pinput: ^5.0.0
  rxdart: ^0.28.0
  shared_preferences: ^2.2.2
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  url_launcher: ^6.1.14

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/static/
    - assets/images/static/walkthrough/
    - assets/images/static/welcome/
    - assets/images/static/forgot/
    - assets/images/static/location/
    - assets/images/static/splash/
    - assets/mp3/
