// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUosOuZQp9-hFQRi7VHT2bZQrT6-winmM',
    appId: '1:738835249826:web:29c3ea46cf397d7c7235fb',
    messagingSenderId: '738835249826',
    projectId: 'cityeat',
    authDomain: 'cityeat.firebaseapp.com',
    storageBucket: 'cityeat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDctuzto9wPKyNWOom0Apn_yfdJt4LTgGU',
    appId: '1:738835249826:android:eb93895e8036cfea7235fb',
    messagingSenderId: '738835249826',
    projectId: 'cityeat',
    storageBucket: 'cityeat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGy4ZgqzpRoZ8Y7JfpXak-tHIlghyk_OE',
    appId: '1:738835249826:ios:17adf2e0f4f40d0c7235fb',
    messagingSenderId: '738835249826',
    projectId: 'cityeat',
    storageBucket: 'cityeat.appspot.com',
    iosBundleId: 'uk.co.cityeats.captain',
  );
}
